repo: "link-card"
canvasCourse: "web-dev-1"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - box-sizing

html:
  - path: "index.html"
    outline: false
    has:
      - "a.link-card"
      - check: 'a h2'
        message: 'Expected to see an `<h2>`—it makes sense to use an `<h2>` in this situation, instead of an `<h1>`, because this card would be part of a larger website'
      - "a dl"
      - "a .btn"
    has_not:
      - check: "hr"
        message: 'The `<hr>` tag should be used for making lines, it’s intended to create divisions in the content—`border` is intended for making lines'
    search:
      - "Dosis"
      - "Dung Beetle"
      - "exclusively on dung"
      - "Learn more"
      - "Arthropoda"
      - "Superfamily"
      - "Scarabaeoidea"
      - "Scarabidae"

css:
  - path: "css/main.css"
    has:
      - ['.link-card']
      - ['.link-card:hover']
      - ['.link-card h2']
    search:
      - "Georgia"
      - "Dosis"
      - "block"
      - "inline-block"
      - "#785439"
      - "#cabdb2"
      - "#512200"
      - "#9a816d"
      - "#dcd4cd"
      - "#f0eee8"

screenshots:
  - path: "index.html"
    sizes: [320]

functionality:
  - path: 'index.html'
    tests:
      - |
        let link = $('.link-card');
        let oldBg = css(link).backgroundColor;

        hover(link, function () {
          if (css(link).backgroundColor == oldBg) return fail('The background colour of the card doesn’t change when hovered')
          pass();
        });
